### ISSUE TITLE
Question: Challenges API

### ISSUE THREAD

**Issue by MichalZalecki** [fabulator/endomondo-api#3]
Hi! Appreciate work put into developing this project. Do you know anything about connecting to challenges API?

**Comment by fabulator** [comment]
Hello, 

Endomondo web app has two parts. The new one and the old one. The new part is using API you can see in this project. The old part does not have any API. Unfortunately, challenges are in the old part of the web app.

Theoretically, you could use MobileApi which I have in this project https://github.com/fabulator/endomondo-api-old Problem is that you would have to sniff requests from the mobile app because I don't know that endpoints.

I have don't have the plan to do it by myself. I could considerate it when Endomondo puts challenges to the new version of their web app. But I would be open to PR.
